/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPreloadRouteImport } from './routes/api/preload'
import { Route as ApiBriefRouteImport } from './routes/api/brief'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreloadRoute = ApiPreloadRouteImport.update({
  id: '/api/preload',
  path: '/api/preload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBriefRoute = ApiBriefRouteImport.update({
  id: '/api/brief',
  path: '/api/brief',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/brief': typeof ApiBriefRoute
  '/api/preload': typeof ApiPreloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/brief': typeof ApiBriefRoute
  '/api/preload': typeof ApiPreloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/brief': typeof ApiBriefRoute
  '/api/preload': typeof ApiPreloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/brief' | '/api/preload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/brief' | '/api/preload'
  id: '__root__' | '/' | '/api/brief' | '/api/preload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBriefRoute: typeof ApiBriefRoute
  ApiPreloadRoute: typeof ApiPreloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preload': {
      id: '/api/preload'
      path: '/api/preload'
      fullPath: '/api/preload'
      preLoaderRoute: typeof ApiPreloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brief': {
      id: '/api/brief'
      path: '/api/brief'
      fullPath: '/api/brief'
      preLoaderRoute: typeof ApiBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBriefRoute: ApiBriefRoute,
  ApiPreloadRoute: ApiPreloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
